### ISSUE TITLE
 how to clear the cached data when database's struct is changed

### ISSUE THREAD

**Issue by qinshimignyue** [moozzyk/EFCache#9] opened 2017-03-30 03:37 UTC
how to clear the cached data when database's struct is changed

**Comment by moozzyk** [comment] 2017-03-30 03:38
it's up to you and depends on what you use to cache results. 

Not a bug - closing.

**Closed by moozzyk** 2017-03-30 03:38 UTC

**Comment by qinshimignyue** [comment] 2017-03-30 04:32
thank's sir:)
