### ISSUE TITLE
NotImplementedException

### ISSUE THREAD

**Issue by ivanlewis** [moozzyk/EFCache#19] opened 2017-08-30 14:29 UTC
var con1 = db.TA001.Where(x => x.tc001n == 5).FirstOrDefault();

System.Data.Entity.Core.EntityCommandExecutionException: 'An error occurred while executing the command definition. See the inner exception for details.'

NotImplementedException: The method or operation is not implemented.

**Comment by moozzyk** [comment] 2017-08-30 14:53
What is the stacktrace?

**Comment by ivanlewis** [comment] 2017-08-30 15:16
If adding 
EntityFrameworkCache.Initialize(new InMemoryCache()); 
next to static void Main(string[] args) { 

Im getting this error

Stack Trace:

   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\Ivan\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 58

![image](https://user-images.githubusercontent.com/835025/29879957-30adceb8-8dc4-11e7-8d2e-f1228e97277d.png)

**Comment by moozzyk** [comment] 2017-08-30 16:34
What is the stack trace of the InnerException? What does the entity look like. From the description you provided I can't tell what the problem is.

**Comment by moozzyk** [comment] 2017-09-06 20:23
The details are not enough to understand/reproduce the problem. Closing.

**Closed by moozzyk** 2017-09-06 20:23 UTC
